### ISSUE TITLE
add way to browserify

### ISSUE THREAD

**Issue by wanderer** [felixge/node-require-all#25]
Its possible. Lets figure out how to do it. :)

**Comment by dougwilson** [comment]
No need to open an issue. Simply open a PR with the solution. I don't do front end development, so will never try to figure it out, but I'm 100% open to accepting a PR with a solution.

**Comment by wanderer** [comment]
ok but you could leave this open so that people know its an open issue.

**Comment by dougwilson** [comment]
I'm not going to leave it open, mainly because it has been brought up multiple times in this issue tracker and IRC and everyone has come to the same conclusion: it's impossible. Because of this, I'm not going to keep an issue open that wont be solved. If you can at least propose a solution here, I'll gladly reopen, otherwise it will remain closed based on all past research.
