### ISSUE TITLE
Filter with regex doesn't work after upgrade from 2.0.0 to 2.1.0 

### ISSUE THREAD

**Issue by bultas** [felixge/node-require-all#46]
not work:

```
require('require-all')({
    dirname: __dirname,
    recursive: true,
    filter: /.+\.test\.js$/
});
```

work
```
require('require-all')({
    dirname: __dirname,
    recursive: true,
    filter: (fileName) => fileName.match(/.+\.test\.js$/)
});
```

**Comment by dougwilson** [comment]
I'm not able to reproduce your issue and our test suite is also showing on Travis CI that regex seems to be working. Can you provide any additional details that can help me reproduce?

**Comment by dougwilson** [comment]
I'm going to close this since I haven't heard anything back. To provide further information: what you posted above does not work in 2.1.0 nor does it work in 2.0.0. This is because your regular expression has no capture group.

**Comment by dougwilson** [comment]
Digging further into it, it seem like it did used to `require()` it, but no longer. But in 2.0.0 the modules were just ending up with the key of `undefined` for all the files, replacing each other. Surely this doesn't even make sense, because how could you access the result of all the files when they all ended up as the same key of `undefined`?

**Comment by dougwilson** [comment]
Closing since I haven't heard anything back.

**Comment by dougwilson** [comment]
I believe that merging #43 will resolve your old behavior.
